# Generated by Django 4.1.5 on 2023-01-14 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='produtos')),
                ('preco_mercado', models.PositiveIntegerField()),
                ('venda', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('garantia', models.CharField(blank=True, max_length=300, null=True)),
                ('return_devolucao', models.CharField(blank=True, max_length=300, null=True)),
                ('visualizacao', models.PositiveIntegerField(default=0)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernando_por', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('endereco_envio', models.CharField(max_length=200)),
                ('subtotal', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('pedido_status', models.CharField(choices=[('Pedido Recebido', 'Pedido Recebido'), ('Pedido Processando', 'Pedido Processando'), ('Pedido a Caminho', 'Pedido a Caminho'), ('Pedido Completado', 'Pedido Completado'), ('Pedido Cancelado', 'Pedido Cancelado')], max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('data_on', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarroProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.PositiveIntegerField()),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.PositiveIntegerField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.carro')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lojaapp.produto')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lojaapp.cliente'),
        ),
    ]
