# Generated by Django 4.1.5 on 2023-01-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_completo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_method',
            field=models.CharField(choices=[('Dinheiro na Entrega', 'Dinheiro na Entrega'), ('Pix', 'Pix')], default='Dinheiro na Entrega', max_length=20),
        ),
    ]
